Repository 0keeper1/nanotest, pull requests merged in 2024-08, with the labels that each got.

#1 Fix expected typo, test fail message typos
  src/lib.h
Labels: improvement

#3 Add examples
  README.md
  example/example_functions.h
  example/example_tests.c
  src/lib.h
Labels: documentation

#5 Add missing assert functions
  example/example_tests.c
  src/lib.h
Labels: improvement

#8 Fix: example/library warnings
  example/example_functions.h
  example/example_tests.c
  src/lib.h
Labels: documentation, enhancement

#10 Fixed: too many arguments provided to function-like macro invocation.
  example/example_tests.c
  src/lib.h
Labels: bugfix
